Allow setting failover network interface options
truenas/midcli pull request #68
Opened 2022-12-01 11:15 UTC by themylogin

2022-12-01 11:15 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119204

2022-12-01 11:21 UTC, themylogin commented
time 2:00

2023-01-12 17:02 UTC, yocalebo requested changes
1. `ipv4_dhcp`, `ipv6_dhcp` are not supported on HA systems
2. `failover_vhid` is no longer required and ignored on SCALE HA
3.

2023-01-12 17:13 UTC, yocalebo commented on midcli/gui/network/interface/create_update.py
>              Input("aliases", delegate=AliasesInputDelegate),
This doesn't seem to enforce or handle the fact if a user provides an ip address without netmask information?

2023-01-16 16:28 UTC, themylogin commented
time 1:00

2023-01-17 12:05 UTC, yocalebo approved these changes

2023-01-17 12:05 UTC, merged